### PR TITLE
Update v37 theme

### PR DESCRIPTION
**Pull request by TheDayG0ne**

### CODE REVIEW

**Comment by pajarorrojo** [comment]
sorry, not relevant. You can create a public fork for your personal project without problem with all these changes you propose.

**Comment by TheDayG0ne** [comment]
Why is it not relevant? Your theme is used by default in ProjectArcade. Also, you didn't mention me in the Readme, for helping with Russian localization

**Comment by pajarorrojo** [comment]
All done in the version 39. Enjoy ;)

**Comment by TheDayG0ne** [comment]
Thank you very much for the theme :)

**Pull request closed without merging**
